---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-pods
  namespace: example-1
  labels:
    component: main
spec:
  namespaceSelector:
    matchNames:
    - example-1
  selector:
    matchLabels:
      istio: monitor
  podMetricsEndpoints:
  - port: http-envoy-prom
    path: stats/prometheus
